### ISSUE TITLE
Geolite DB in Docker Error

### ISSUE THREAD

**Issue by abmurksi** [Boerderij/docker-Varken#1]
First: This is brilliant, thank you so much. Been using your old scripts for a year now.

I setup the container and see the stats in Grafana.
As soon as I have one user streaming, I get the error in Docker log:

FileNotFoundError: [Errno 2] No such file or directory: '/run/s6/services/Varken/data/GeoLite2-City.tar.gz'

Do I need to manually copy the GeoLite db somewhere?

**Comment by Grygon** [comment]
Having this issue too, my full log is below, in case that's any help:

```
2018-12-10 16:33:26 : INFO : __init__ : Running job Every 30 seconds do threaded(<bound method TautulliAPI.get_activity of <tautulli-1>>) (last run: 2018-12-10 16:32:56, next run: 2018-12-10 16:33:26)
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/app/varken/helpers.py", line 35, in geo_lookup
    dbinfo = os.stat(dbfile)
FileNotFoundError: [Errno 2] No such file or directory: '/run/s6/services/Varken/data/GeoLite2-City.mmdb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/app/varken/tautulli.py", line 44, in get_activity
    geodata = geo_lookup(session.ip_address_public)
  File "/app/varken/helpers.py", line 41, in geo_lookup
    geoip_download()
  File "/app/varken/helpers.py", line 20, in geoip_download
    urlretrieve(url, tar_dbfile)
  File "/usr/lib/python3.6/urllib/request.py", line 258, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/run/s6/services/Varken/data/GeoLite2-City.tar.gz'
```

**Comment by DirtyCajunRice** [comment]
commenting in the merge request
